// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestione_spese.Data;

#nullable disable

namespace gestione_spese.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319171711_MigrazioneDefinitiva")]
    partial class MigrazioneDefinitiva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("GruppoUtente", b =>
                {
                    b.Property<int>("GruppiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtentiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GruppiId", "UtentiId");

                    b.HasIndex("UtentiId");

                    b.ToTable("UtenteGruppo", (string)null);
                });

            modelBuilder.Entity("gestione_spese.Models.DivisioneSpesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Spesa_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Utente_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Spesa_ID");

                    b.HasIndex("Utente_ID");

                    b.ToTable("Divisioni");
                });

            modelBuilder.Entity("gestione_spese.Models.Gruppo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Attivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceInvito")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gruppi");
                });

            modelBuilder.Entity("gestione_spese.Models.Riepilogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AChiDeve_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChiDeve_ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCalcolo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gruppo_ID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool>("Pagato")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AChiDeve_ID");

                    b.HasIndex("ChiDeve_ID");

                    b.HasIndex("Gruppo_ID");

                    b.ToTable("Riepiloghi");
                });

            modelBuilder.Entity("gestione_spese.Models.Spesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ChiPaga_ID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSpesa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gruppo_ID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Importo")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("ChiPaga_ID");

                    b.HasIndex("Gruppo_ID");

                    b.ToTable("Spese");
                });

            modelBuilder.Entity("gestione_spese.Models.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataIscrizione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("GruppoUtente", b =>
                {
                    b.HasOne("gestione_spese.Models.Gruppo", null)
                        .WithMany()
                        .HasForeignKey("GruppiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestione_spese.Models.Utente", null)
                        .WithMany()
                        .HasForeignKey("UtentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("gestione_spese.Models.DivisioneSpesa", b =>
                {
                    b.HasOne("gestione_spese.Models.Spesa", "Spesa")
                        .WithMany("Divisioni")
                        .HasForeignKey("Spesa_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestione_spese.Models.Utente", "Utente")
                        .WithMany("DivisioniSpesa")
                        .HasForeignKey("Utente_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Spesa");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("gestione_spese.Models.Riepilogo", b =>
                {
                    b.HasOne("gestione_spese.Models.Utente", "UtenteACuiDeve")
                        .WithMany("RiepiloghettiRicevuti")
                        .HasForeignKey("AChiDeve_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gestione_spese.Models.Utente", "UtenteCheDeve")
                        .WithMany("RiepiloghettiDovuti")
                        .HasForeignKey("ChiDeve_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gestione_spese.Models.Gruppo", "Gruppo")
                        .WithMany("Riepiloghetti")
                        .HasForeignKey("Gruppo_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gruppo");

                    b.Navigation("UtenteACuiDeve");

                    b.Navigation("UtenteCheDeve");
                });

            modelBuilder.Entity("gestione_spese.Models.Spesa", b =>
                {
                    b.HasOne("gestione_spese.Models.Utente", "UtenteChePaga")
                        .WithMany("SpesePagate")
                        .HasForeignKey("ChiPaga_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("gestione_spese.Models.Gruppo", "Gruppo")
                        .WithMany("Spese")
                        .HasForeignKey("Gruppo_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gruppo");

                    b.Navigation("UtenteChePaga");
                });

            modelBuilder.Entity("gestione_spese.Models.Gruppo", b =>
                {
                    b.Navigation("Riepiloghetti");

                    b.Navigation("Spese");
                });

            modelBuilder.Entity("gestione_spese.Models.Spesa", b =>
                {
                    b.Navigation("Divisioni");
                });

            modelBuilder.Entity("gestione_spese.Models.Utente", b =>
                {
                    b.Navigation("DivisioniSpesa");

                    b.Navigation("RiepiloghettiDovuti");

                    b.Navigation("RiepiloghettiRicevuti");

                    b.Navigation("SpesePagate");
                });
#pragma warning restore 612, 618
        }
    }
}
